export const SISGES_ICON_CATEGORIES = [
  'existentes',
  'datos',
  'cobranza',
  'usuarios',
  'archivos',
  'reportes',
  'movil',
  'comunicaciones',
  'servicios',
  'seguridad',
  'generales',
] as const;

export type SisgesIconCategory =
  (typeof SISGES_ICON_CATEGORIES)[number];

export const SISGES_ICON_NAMES = [
  // Claves ya utilizadas por menu-modulos. No renombrar durante la migración.
  'database',
  'dollar-sign',
  'users',
  'bar-chart',
  'file-text',
  'smartphone',
  'monitor',
  'briefcase',
  'target',
  'mail',
  'phone',
  'user',
  'key',
  'shield',

  // Catálogo SISGES.
  'module-default',
  'dashboard',
  'data-management',
  'database-upload',
  'database-process',
  'database-download',
  'collection-management',
  'collection-strategy',
  'portfolio',
  'map-zones',
  'debtor-management',
  'unassign-users',
  'letter-management',
  'dialer-management',
  'response-catalog',
  'altitude-management',
  'letter-alert',
  'user-management',
  'user-settings',
  'user-assignment',
  'password-change',
  'file-management',
  'file-upload',
  'scheduled-upload',
  'receipt-assignment',
  'daily-settlement',
  'file-download',
  'gtelcom-download',
  'general-reports',
  'priority-management',
  'effectiveness-report',
  'identity-search',
  'client-reports',
  'field-daily-report',
  'call-daily-report',
  'ladder-report',
  'reports',
  'mobile-management',
  'image-management',
  'download-center',
  'services',
  'online-production',
  'predictive-dialer',
  'progressive-dialer',
  'initial-settings',
  'security',
  'permissions',
  'profiles',
  'groups',
  'modules',
  'search',
  'filter',
  'calendar',
  'history',
  'audit',
  'notification',
  'warning',
  'success',
  'error',
  'location',
  'document',
  'folder',
  'download',
  'upload',
  'export',
  'import',
  'settings',
  'automation',
  'integration',
  'analytics',
  'money',
  'payments',
  'customer',
  'agent',
  'campaign',
] as const;

export type SisgesIconName =
  (typeof SISGES_ICON_NAMES)[number];

export interface SisgesIconDefinition {
  readonly name: SisgesIconName;
  readonly label: string;
  readonly category: SisgesIconCategory;
  readonly keywords: readonly string[];
  readonly legacy: boolean;
}
