export const FICHA_DEUDOR_PANEL = {
  DATOS_ADICIONALES: 'DATOS ADICIONALES',
  TELEFONOS_REFERENCIADOS: 'TELÉFONOS REFERENCIADOS',
  DIRECCIONES_REFERENCIADAS: 'DIRECCIONES REFERENCIADAS',
  GESTION_REALIZADA: 'GESTIÓN REALIZADA',
  ESTADO_GESTION_REALIZADA: 'ESTADO DE GESTIÓN REALIZADA',
} as const;

export type FichaDeudorPanel =
  (typeof FICHA_DEUDOR_PANEL)[keyof typeof FICHA_DEUDOR_PANEL];